[style]
font_size = 14
item_padding_horizontal = 12
item_padding_vertical = 4
item_margin = 2
item_min_width = 70
item_border_radius = 6

icon_padding_left = 6
icon_padding_right = 4

separator_height = 1
separator_margin_vertical = 4
separator_margin_horizontal = 2

menu_padding = 4
